language: python
dist: trusty # librdkafka support begins at Trusty.
python:
  - "3.6" # Advertised support
  - "3.6-dev" # Check we'll keep working in future
before_install:
  - wget -qO - http://packages.confluent.io/deb/3.2/archive.key | sudo apt-key add - # Use the confluent repository
  - sudo add-apt-repository "deb [arch=amd64] http://packages.confluent.io/deb/3.2 stable main"
  - sudo apt-get update -qq # Update quietly.
  - sudo apt-get install -y librdkafka-dev librdkafka1
install: "pip install --editable .[develop]"
script: pytest
